# Generated by Django 4.1.7 on 2023-03-11 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='direcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='registro_ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('usuario', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50, unique=True)),
                ('mac', models.CharField(blank=True, max_length=50, null=True)),
                ('tlf', models.CharField(blank=True, max_length=50, null=True)),
                ('mactlf', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ip.cargos')),
                ('direccion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ip.direcciones')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
