# Generated by Django 4.0.6 on 2022-11-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_direccion_modificacion_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
