# Generated by Django 4.0.6 on 2022-11-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modificacion',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
    ]
