# Generated by Django 4.0.6 on 2022-12-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_modificacion_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='created',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='created',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='modified',
        ),
    ]
