# Generated by Django 4.0.1 on 2022-01-16 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('num_operacion', models.IntegerField()),
                ('Complejo', models.CharField(max_length=255, null=True)),
                ('Empresa', models.CharField(max_length=255, null=True)),
                ('Cod_barra', models.CharField(max_length=255, null=True)),
                ('peso_bruto', models.DecimalField(decimal_places=5, max_digits=10)),
                ('Num_guia_onafin', models.CharField(max_length=255, null=True)),
                ('num_caja', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Derechante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=60)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='claculo_testigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('Cod_barra', models.CharField(max_length=255, null=True)),
                ('Fecha_certificado', models.DateField(auto_now=True)),
                ('Ley', models.DecimalField(decimal_places=5, max_digits=10)),
                ('Peso_final', models.DecimalField(decimal_places=5, max_digits=10)),
                ('Fecha_fixing', models.DateField(auto_now=True)),
                ('Fixing', models.DecimalField(decimal_places=5, max_digits=10)),
                ('Fecha_tdc', models.DateField(auto_now=True)),
                ('TDC', models.DecimalField(decimal_places=5, max_digits=10)),
                ('Barra', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.barra')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='calculo_barra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('Cod_barra', models.CharField(max_length=255, null=True)),
                ('Fecha_certificado', models.DateField(auto_now=True)),
                ('Ley', models.DecimalField(decimal_places=5, max_digits=10)),
                ('Peso_final', models.DecimalField(decimal_places=5, max_digits=10)),
                ('Fecha_fixing', models.DateField(auto_now=True)),
                ('Fixing', models.DecimalField(decimal_places=5, max_digits=10)),
                ('Fecha_tdc', models.DateField(auto_now=True)),
                ('TDC', models.DecimalField(decimal_places=5, max_digits=10)),
                ('Barra', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.barra')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='barra',
            name='Derechante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.derechante'),
        ),
        migrations.AddField(
            model_name='barra',
            name='Estatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.estatus'),
        ),
        migrations.AddField(
            model_name='barra',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
