# Generated by Django 4.0.1 on 2022-01-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_derechante_tipo_alter_estatus_tipo_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculo_barra',
            name='Fecha_certificado',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='calculo_barra',
            name='Fecha_fixing',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='calculo_barra',
            name='Fecha_tdc',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='claculo_testigo',
            name='Fecha_certificado',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='claculo_testigo',
            name='Fecha_fixing',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='claculo_testigo',
            name='Fecha_tdc',
            field=models.DateField(),
        ),
    ]
