# Generated by Django 4.0.1 on 2022-01-16 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_calculo_barra_fecha_certificado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barra',
            name='usuario',
        ),
    ]
