# Generated by Django 4.0.1 on 2022-01-18 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_barra_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barra',
            name='Estatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.estatus'),
        ),
    ]
