# Generated by Django 4.0.1 on 2022-01-19 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0006_alter_barra_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barra',
            name='Estatus',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('BS', models.DecimalField(decimal_places=5, max_digits=10)),
                ('USD', models.DecimalField(decimal_places=5, max_digits=10)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
