# Generated by Django 4.0.1 on 2022-01-19 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_barra_estatus_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculo_barra',
            name='Cod_barra',
        ),
    ]
