# Generated by Django 4.0.1 on 2022-01-19 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_calculo_barra_cod_barra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claculo_testigo',
            name='Cod_barra',
        ),
        migrations.AddField(
            model_name='calculo_barra',
            name='valores',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.valor'),
        ),
        migrations.AddField(
            model_name='claculo_testigo',
            name='valores',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.valor'),
        ),
    ]
