# Generated by Django 4.0.1 on 2022-01-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_claculo_testigo_cod_barra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculo_barra',
            name='valores',
        ),
        migrations.RemoveField(
            model_name='claculo_testigo',
            name='valores',
        ),
        migrations.AddField(
            model_name='calculo_barra',
            name='BS',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='calculo_barra',
            name='USD',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='claculo_testigo',
            name='BS',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='claculo_testigo',
            name='USD',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='valor',
        ),
    ]
