# Generated by Django 4.0.1 on 2022-01-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_barra_calculado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barra',
            name='calculado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
