# Generated by Django 4.0.1 on 2022-01-21 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_barra_calculado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barra',
            name='calculado',
        ),
        migrations.AlterField(
            model_name='calculo_barra',
            name='Barra',
            field=models.OneToOneField(error_messages={'unique': 'The Geeks Field you entered is not unique.'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.barra'),
        ),
    ]
