# Generated by Django 4.0.1 on 2022-01-21 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_barra_calculado_alter_calculo_barra_barra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculo_barra',
            name='Barra',
            field=models.OneToOneField(error_messages={'unique': 'La Barra ya esta calculada!'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.barra'),
        ),
        migrations.AlterField(
            model_name='claculo_testigo',
            name='Barra',
            field=models.OneToOneField(error_messages={'unique': 'La Barra ya esta calculada!'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.barra'),
        ),
    ]
