# Generated by Django 4.1.7 on 2023-03-11 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='direcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='reporte_soporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('usuario', models.CharField(max_length=50)),
                ('observacion', models.TextField()),
                ('tlf', models.CharField(blank=True, max_length=50, null=True)),
                ('estatus', models.BooleanField(blank=True, null=True)),
                ('analista', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reporte.direcciones')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
